const types = {
  FETCH_PICTURES: "FETCH_PICTURES",
  UPDATE_LOADING: "UPDATE_LOADING",
  THROW_PICTURES_ERROR: "THROW_PICTURES_ERROR",
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
};

export default types;
